/**
 * 方案2：在 Layout 中使用 Suspense 包装所有页面
 * 这样可以在页面加载时自动显示 loading.tsx
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Loading from "./loading";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* 使用 Suspense 包装，当页面组件加载时会显示 loading */}
				<Suspense fallback={<Loading />}>
					{children}
				</Suspense>
			</body>
		</html>
	);
}

